# Generated by Django 4.2.2 on 2023-07-23 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_preference_alter_formentry_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formentry',
            name='preference',
        ),
        migrations.AddField(
            model_name='formentry',
            name='preferences',
            field=models.ManyToManyField(to='forms.preference'),
        ),
        migrations.AlterField(
            model_name='formentry',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='WorkshopPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_passes', models.IntegerField(default=0)),
                ('allocated_passes', models.IntegerField(default=0)),
                ('preference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forms.preference')),
            ],
        ),
    ]
