# Generated by Django 4.2.2 on 2023-07-23 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_remove_formentry_preference_formentry_preferences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshoppass',
            name='form_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.formentry'),
        ),
        migrations.AlterField(
            model_name='workshoppass',
            name='preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.preference'),
        ),
    ]
